### PR TITLE
Run the project inside a Docker container

### PR DESCRIPTION
**Pull request by rafaelji**
I added docker configuration files to run the node and project inside Docker. This causes everyone to have the same configuration. In the future we can facilitate the deploy process if we use an CI / CD process.

### CODE REVIEW

**Comment by eduludi** [comment]
Thanks @rafaelji for this PR!

We understand docker is a great development/deployment tool, but we don't want to force `alps-react` users to use it. So, in order to make the project work as standalone as possible, I would suggest to add a "Docker" section into README, instead of replacing its basic/standalone usage. 

Send an updated REAME, and we will be happy to merge it.

**Comment by rafaelji** [comment]
Hi @eduludi , thanks for answer me.
I got your point, as soon I can update the README I will do it!
Should I create a new branch and PR for this or should I do the changes here?

**Comment by eduludi** [comment]
> "Should I create a new branch and PR for this or should I do the changes here?"

@rafaelji I think is better if you just do it here. Thanks!

**Comment by rafaelji** [comment]
Done! :)

**Pull request merged**
